[{"name": "test.test_read_series.ReadSeries.test_empty", "status": "errored", "message": "name 'pd' is not defined", "passed": false, "points": ["p03-13.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e13_read_series/test/test_read_series.py\", line 30, in test_empty\n    s = read_series()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e13_read_series/src/read_series.py\", line 5, in read_series\n    return pd.Series()\n"]}, {"name": "test.test_read_series.ReadSeries.test_error", "status": "passed", "message": "", "passed": true, "points": ["p03-13.1"], "backtrace": []}, {"name": "test.test_read_series.ReadSeries.test_first", "status": "errored", "message": "name 'pd' is not defined", "passed": false, "points": ["p03-13.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e13_read_series/test/test_read_series.py\", line 22, in test_first\n    s = read_series()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e13_read_series/src/read_series.py\", line 5, in read_series\n    return pd.Series()\n"]}]