[{"name": "test.test_rows_and_columns.RowsAndColumns.test_column_content", "status": "failed", "message": "0 != 5 : Incorrect number of elements in list", "passed": false, "points": ["p02-11.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e11_rows_and_columns/test/test_rows_and_columns.py\", line 52, in test_column_content\n    self.assertEqual(len(columns), m, msg=\"Incorrect number of elements in list\")\n"]}, {"name": "test.test_rows_and_columns.RowsAndColumns.test_columns_types", "status": "failed", "message": "0 != 5 : Incorrect number of elements in list", "passed": false, "points": ["p02-11.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e11_rows_and_columns/test/test_rows_and_columns.py\", line 32, in test_columns_types\n    self.assertEqual(len(columns), 5, msg=\"Incorrect number of elements in list\")\n"]}, {"name": "test.test_rows_and_columns.RowsAndColumns.test_row_content", "status": "failed", "message": "0 != 4 : Incorrect number of elements in list", "passed": false, "points": ["p02-11.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e11_rows_and_columns/test/test_rows_and_columns.py\", line 41, in test_row_content\n    self.assertEqual(len(rows), n, msg=\"Incorrect number of elements in list\")\n"]}, {"name": "test.test_rows_and_columns.RowsAndColumns.test_row_types", "status": "failed", "message": "0 != 4 : Incorrect number of elements in list", "passed": false, "points": ["p02-11.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e11_rows_and_columns/test/test_rows_and_columns.py\", line 24, in test_row_types\n    self.assertEqual(len(rows), 4, msg=\"Incorrect number of elements in list\")\n"]}]