[{"name": "test.test_word_frequencies.WordFrequencies.test_calls", "status": "failed", "message": "Expected 'open' to have been called.", "passed": false, "points": ["p02-04.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e04_word_frequencies/test/test_word_frequencies.py\", line 28, in test_calls\n    o.assert_called()\n", "  File \"/usr/lib/python3.10/unittest/mock.py\", line 888, in assert_called\n    raise AssertionError(msg)\n"]}, {"name": "test.test_word_frequencies.WordFrequencies.test_first", "status": "errored", "message": "'creating'", "passed": false, "points": ["p02-04.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e04_word_frequencies/test/test_word_frequencies.py\", line 18, in test_first\n    self.assertEqual(d['creating'], 3, msg=\"Incorrect count for word 'creating'!\")\n"]}]