[{"name": "test.test_column_comparison.ColumnComparison.test_content", "status": "errored", "message": "index 0 is out of bounds for axis 0 with size 0", "passed": false, "points": ["p03-01.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e01_column_comparison/test/test_column_comparison.py\", line 44, in test_content\n    np.testing.assert_allclose(row, result[ri], err_msg=\"Incorrect result for array\\n%s\"%a)\n"]}, {"name": "test.test_column_comparison.ColumnComparison.test_greater", "status": "passed", "message": "", "passed": true, "points": ["p03-01.1"], "backtrace": []}, {"name": "test.test_column_comparison.ColumnComparison.test_shape", "status": "errored", "message": "tuple index out of range", "passed": false, "points": ["p03-01.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e01_column_comparison/test/test_column_comparison.py\", line 32, in test_shape\n    self.assertEqual(result.shape[1], m, msg=\"The result should have as many columns as the input!\")\n"]}]