[{"name": "test.test_almost_meeting_lines.AlmostMeetingLines.test_first", "status": "errored", "message": "not enough values to unpack (expected 2, got 0)", "passed": false, "points": ["p03-08.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e08_almost_meeting_lines/test/test_almost_meeting_lines.py\", line 38, in test_first\n    (x, y), exact = almost_meeting_lines(*p)\n"]}, {"name": "test.test_almost_meeting_lines.AlmostMeetingLines.test_inconsistent", "status": "errored", "message": "not enough values to unpack (expected 2, got 0)", "passed": false, "points": ["p03-08.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e08_almost_meeting_lines/test/test_almost_meeting_lines.py\", line 59, in test_inconsistent\n    (x, y), exact = almost_meeting_lines(*p)\n"]}, {"name": "test.test_almost_meeting_lines.AlmostMeetingLines.test_types", "status": "errored", "message": "not enough values to unpack (expected 2, got 0)", "passed": false, "points": ["p03-08.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e08_almost_meeting_lines/test/test_almost_meeting_lines.py\", line 26, in test_types\n    (x, y), exact = almost_meeting_lines(*p)\n"]}, {"name": "test.test_almost_meeting_lines.AlmostMeetingLines.test_underdetermined", "status": "errored", "message": "not enough values to unpack (expected 2, got 0)", "passed": false, "points": ["p03-08.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e08_almost_meeting_lines/test/test_almost_meeting_lines.py\", line 50, in test_underdetermined\n    (x, y), exact = almost_meeting_lines(*p)\n"]}]