[{"name": "test.test_file_count.FileCount.test_calls", "status": "failed", "message": "Expected 'open' to have been called once. Called 0 times.", "passed": false, "points": ["p02-06.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e06_file_count/test/test_file_count.py\", line 29, in test_calls\n    o.assert_called_once()\n", "  File \"/usr/lib/python3.10/unittest/mock.py\", line 898, in assert_called_once\n    raise AssertionError(msg)\n"]}, {"name": "test.test_file_count.FileCount.test_first", "status": "failed", "message": "0 != 8 : Wrong number of lines for file 'test.txt'!", "passed": false, "points": ["p02-06.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e06_file_count/test/test_file_count.py\", line 21, in test_first\n    self.assertEqual(l, 8, msg=\"Wrong number of lines for file 'test.txt'!\")\n"]}, {"name": "test.test_file_count.FileCount.test_main", "status": "failed", "message": "0 != 7 : Wrong number of calls to function 'file_count' for 7 command line parameters!", "passed": false, "points": ["p02-06.2"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e06_file_count/test/test_file_count.py\", line 39, in test_main\n    self.assertEqual(fc.call_count, n,\n"]}]