[{"name": "unittest.loader._FailedTest.test.test_radial_fade", "status": "errored", "message": "Failed to import test module: test.test_radial_fade\nTraceback (most recent call last):\n  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n    module = self._get_module_from_name(name)\n  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n    __import__(name)\n  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e12_radial_fade/test/test_radial_fade.py\", line 7, in <module>\n    import matplotlib.pyplot as plt\nModuleNotFoundError: No module named 'matplotlib'\n", "passed": false, "points": [], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/usr/lib/python3.10/unittest/loader.py\", line 34, in testFailure\n    raise self._exception\n"]}]